### ISSUE TITLE
Missing zoom 12 terrarium tiles

### ISSUE THREAD

**Issue by nvkelso** [tilezen/joerd#87]
Developer support request reports **193 missing tiles**, see the "full list" attachment below.

Endpoint used:
- https://s3.amazonaws.com/elevation-tiles-prod/terrarium/

Example: 
- https://s3.amazonaws.com/terrarium/12/331/921.png

Full list:
- [missing-tiles.txt](https://github.com/tilezen/joerd/files/387138/missing-tiles.txt)

**Comment by zerebubuth** [comment]
I've cleaned up the list of missing tiles from S3, which included all those in the attached list :relieved:

A first pass through those rendered a few, but the majority had errors. I think I've fixed the problems, and the rest are now rendering.

**Comment by jan-tosovsky-cz** [comment]
I can confirm it has been partially fixed. Now only 62 remains:
https://s3.amazonaws.com/terrarium/12/[341..342]/[882..912].png

**Comment by nvkelso** [comment]
@jan-tosovsky-cz Thanks for the update! We'll keep this issue open until the remaining 62 are also resolved.

**Comment by nvkelso** [comment]
Here's an example tile that's still missing:

- http://a.tile.openstreetmap.org/12/341/882.png

Which is water up in the Arctic ocean in high latitudes:

- http://tangrams.github.io/bubble-wrap/#12/71.0027/-149.9854

Likely sourced from ETOPO1.

@jan-tosovsky-cz Those are over-zoomed bathymetry tiles with poor resolution. Are they critical for your workflow?

**Comment by jan-tosovsky-cz** [comment]
@nvkelso thanks for analysis. They are not critical. My aim is to get elevation range for every particular tile. I can average missing values from adjacent ones. I am just trying avoid this tweaking (= additional work). Especially when final processing is planned not before few next weeks.

**Comment by zerebubuth** [comment]
My latest calculations show that there should be no missing tiles now. I almost can't believe it! Please, please let me know if you do find any, because I'm sure there must be a few hiding away somewhere :wink:

**Comment by jan-tosovsky-cz** [comment]
I can confirm there are no missing tiles for zoom 12 (terrarium) any more. Thanks guys!

**Comment by nvkelso** [comment]
Great to hear, thanks for checking @jan-tosovsky-cz!
